"""Agregar columna seguimiento a Problema

Revision ID: 2cb8bc09cf15
Revises: 44a3911f501a
Create Date: 2024-08-09 10:07:37.617709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb8bc09cf15'
down_revision = '44a3911f501a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguimiento', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('seguimiento')

    # ### end Alembic commands ###
