"""Add avances field to Problema

Revision ID: 44a3911f501a
Revises: 4f58ea5c1d87
Create Date: 2024-08-09 09:05:59.944029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a3911f501a'
down_revision = '4f58ea5c1d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avances', sa.Text(), nullable=True))
        batch_op.drop_column('vances')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vances', sa.TEXT(), nullable=True))
        batch_op.drop_column('avances')

    # ### end Alembic commands ###
