"""Add avances to Problema

Revision ID: 4f58ea5c1d87
Revises: 5b00963d2f4f
Create Date: 2024-08-09 09:02:34.595625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f58ea5c1d87'
down_revision = '5b00963d2f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vances', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('vances')

    # ### end Alembic commands ###
