"""Agregar columna actualizaciones a Problema

Revision ID: 3841e1aaf855
Revises: e1c8d46d08af
Create Date: 2024-07-16 10:45:37.836907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3841e1aaf855'
down_revision = 'e1c8d46d08af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actualizaciones', sa.Text(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('actualizaciones')

    # ### end Alembic commands ###
