"""Add estado_problema to Problema

Revision ID: afe54791e8ee
Revises: 3841e1aaf855
Create Date: 2024-07-16 15:30:49.611305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe54791e8ee'
down_revision = '3841e1aaf855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_problema', sa.String(length=50), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('estado_problema')

    # ### end Alembic commands ###