"""Agregar columnas de fecha de compromiso y fecha de solución a Problema

Revision ID: d87bcbbd774f
Revises: e6e23414c9d1
Create Date: 2024-08-11 08:09:55.753734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87bcbbd774f'
down_revision = 'e6e23414c9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_compromiso', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_solucion', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('fecha_solucion')
        batch_op.drop_column('fecha_compromiso')

    # ### end Alembic commands ###
