"""Add reportado_por_operativo to Problema

Revision ID: e1c8d46d08af
Revises: 
Create Date: 2024-06-05 18:28:36.338598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c8d46d08af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reportado_por_operativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('reportado_por_operativo')

    # ### end Alembic commands ###
