"""Add ultima_fecha_seguimiento to Problema

Revision ID: e6e23414c9d1
Revises: 2cb8bc09cf15
Create Date: 2024-08-09 14:59:01.942000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e23414c9d1'
down_revision = '2cb8bc09cf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_fecha_seguimiento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('ultima_fecha_seguimiento')

    # ### end Alembic commands ###
